# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1659, 1396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton.setObjectName("pushbutton")
        self.gridLayout.addWidget(self.pushbutton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1659, 29))
        self.menubar.setObjectName("menubar")
        self.menuhello = QtWidgets.QMenu(self.menubar)
        self.menuhello.setObjectName("menuhello")
        self.menuOpen = QtWidgets.QMenu(self.menuhello)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.actionHello1 = QtWidgets.QAction(MainWindow)
        self.actionHello1.setObjectName("actionHello1")
        self.actionHello2 = QtWidgets.QAction(MainWindow)
        self.actionHello2.setObjectName("actionHello2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuOpen.addAction(self.actionHello1)
        self.menuOpen.addAction(self.actionHello2)
        self.menuhello.addSeparator()
        self.menuhello.addAction(self.menuOpen.menuAction())
        self.menuhello.addAction(self.actionSave)
        self.menuhello.addSeparator()
        self.menuhello.addAction(self.actionExit)
        self.menubar.addAction(self.menuhello.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HelloWorld!"))
        self.label.setText(_translate("MainWindow", "Hello World"))
        self.pushbutton.setText(_translate("MainWindow", "hello"))
        self.menuhello.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionHello1.setText(_translate("MainWindow", "Hello1"))
        self.actionHello2.setText(_translate("MainWindow", "Hello2"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
